# Specifies the GHC version and set of packages available
resolver: lts-12.18

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process.git
    commit: 660d554f6acd2dba8b605c84e8fa69e45708bc14
  extra-dep: true
- location:
    git: https://github.com/haskell-distributed/distributed-process-systest.git
    commit: d43a6ee475b1ea2d3c5edcf460517a948eba7a78
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- rematch-0.2.0.0
- exceptions-0.10.0
- network-transport-tcp-0.6.0 # works locally without it but doesn't pass CI

# Override default flag values for local packages and extra-deps
flags: {}
